# Generated by Django 5.0.6 on 2024-06-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=32, verbose_name="笔记类别")),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("textContent", models.TextField(verbose_name="文本内容")),
                (
                    "picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="note", verbose_name="图片"
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True, null=True, upload_to="note", verbose_name="音频"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="笔记创建时间"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="笔记更新时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
