# Generated by Django 5.0.6 on 2024-06-08 11:24

import note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=note.models.user_directory_path, verbose_name='音频'),
        ),
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=note.models.user_directory_path, verbose_name='图片'),
        ),
    ]
