# Generated by Django 5.0.6 on 2024-06-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=32, unique=True, verbose_name="账户"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                ("nickname", models.CharField(max_length=50, verbose_name="用户名称")),
                ("mobile", models.CharField(max_length=255, verbose_name="手机号")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="用户信息创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="用户信息更新时间"),
                ),
            ],
        ),
    ]
